### ISSUE TITLE
Plugin doesn't identify configuration changes

### ISSUE THREAD

**Issue by inode-** [federicodotta/HandyCollaborator#1]
If the plugin is loaded by default at burp startup it will use the default burp collaborator. If the user change the project options to use a custom collaborator server the plugin will continue to use the default one.

The only way to force the plugin to load the custom collaborator server is to unload and then reload the plugin.

**Comment by 0x-nope** [comment]
Yes, i can confirm this.

**Comment by federicodotta** [comment]
The issue should be fixed with the last commits. Now Handy Collaborator handles configuration changes (and if you change Collaborator server the plugin polls old and new Collaborator in order get all interactions) and collaborator disabling and re-enabling. 

Please try the new version and let me know if now it handles changes correctly.

Federico
